-compile([{parse_transform, lager_transform}]).
-define(ERR(Format, Params), lager:error(Format, Params)).
-define(INF(Format, Params), lager:info(Format, Params)).
-define(DBG(Format, Params), lager:debug(Format, Params)).