-define(L2B(L), list_to_binary(L)).
-define(I2B(Int), list_to_binary(integer_to_list(Int))).
-define(L2A(L), try list_to_existing_atom(L) catch _:_ -> list_to_atom(L) end).
-define(B2I(B), list_to_integer(binary_to_list(B))).
-define(B2A(Bin), ?L2A(binary_to_list(Bin))).
-define(B2T(B), binary_to_term(B)).
-define(L2I(L), try list_to_integer(L) of I -> I catch _:_ -> undefined end).